config/routes.rb
Rails.application.routes.draw do

  resources :lezionis
  devise_for :trainers
  devise_for :users
  root 'pages#home'

  get 'about' => 'pages#about'

end

app/models/lezioni.rb
class Lezioni < ActiveRecord::Base
	belongs_to :trainer
end

app/models/trainer.rb
class Trainer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lezionis
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :surname, :date_of_birth])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :surname, :date_of_birth])
  end
end

app/controllers/lezionis_controller.rb
class LezionisController < ApplicationController
  before_action :set_lezioni, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_trainer!, except: [:index, :show]
  before_action :check_trainer, only: [:edit, :update, :destroy]

  # GET /lezionis
  # GET /lezionis.json
  def index
    @lezionis = Lezioni.all
  end

  # GET /lezionis/1
  # GET /lezionis/1.json
  def show
  end

  # GET /lezionis/new
  def new
    @lezioni = current_trainer.lezionis.build
  end

  # GET /lezionis/1/edit
  def edit
  end

  # POST /lezionis
  # POST /lezionis.json
  def create
    @lezioni = current_trainer.lezionis.build(lezioni_params)

    respond_to do |format|
      if @lezioni.save
        format.html { redirect_to @lezioni, notice: 'Lezioni was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /lezionis/1
  # PATCH/PUT /lezionis/1.json
  def update
    respond_to do |format|
      if @lezioni.update(lezioni_params)
        format.html { redirect_to @lezioni, notice: 'Lezioni was successfully updated.' }
        format.json { render :show, status: :ok, location: @lezioni }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /lezionis/1
  # DELETE /lezionis/1.json
  def destroy
    @lezioni.destroy
    respond_to do |format|
      format.html { redirect_to lezionis_url, notice: 'Lezioni was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lezioni
      @lezioni = Lezioni.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lezioni_params
      params.require(:lezioni).permit(:titolo, :prezzo, :descrizione, :date, :park, :meeting_point, :equipment, :city, :time, :numero_di_iscritti, :minutes)
    end

    def check_trainer
      if current_trainer != @lezioni.trainer
        redirect_to root_url, alert: "Non hai accesso a questa pagina"
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
  end

  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lezionis_helper.rb
module LezionisHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
    <footer class="page-footer indigo darken-3">
      <div class="container">
        <h5 class="center orange-text text-accent-4 social">Seguici sui nostri canali social!</h5>
        <div class="row center">
           <div class="col s2 offset-s3"><%= link_to icon('envelope', class: 'fa-2x orange-text text-accent-4'), 'mailto:info@fitjoy.it', :title => "Mandaci una mail"  %></div>
           <div class="col s2"><%= link_to icon('facebook-square', class: 'fa-2x orange-text text-accent-4'), 'https://www.facebook.com/FitJoy-101551826567466', :title => "Contattaci su Facebook" %></div>
           <div class="col s2"><%= link_to icon('instagram', class: 'fa-2x orange-text text-accent-4'), 'https://www.instagram.com/fitjoy.it/', :title => "Seguici su Instagram"  %></div>
        </div>
      </div>
      <div class="footer-copyright indigo darken-4">
        <div class="container center">
        © 2016 <%= link_to 'FitJoy', 'http://fitjoy.it', :class => "orange-text text-accent-4", :title => "FitJoy" %> All rights reserved.
        </div>
      </div>
    </footer>

app/views/layouts/_header.html.erb
  <header class="navbar-fixed">

    <!-- Dropdown navbar desktop -->
    <ul id="dropdown-login" class="dropdown-content">
      <li><%= link_to 'Utente', new_user_session_path, :class => "indigo darken-4 white-text", :title => "Log in utente" %></li>
      <li><%= link_to 'Allenatore', new_trainer_session_path, :class => "orange accent-4 white-text", :title => "Log in allenatore" %></li>
    </ul>

    <ul id="dropdown-registrazione" class="dropdown-content">
      <li><%= link_to 'Nuovo utente', new_user_registration_path, :class => "indigo darken-4 white-text", :title => "Registrazione utente" %></li>
      <li><%= link_to 'Nuovo allenatore', new_trainer_registration_path, :class => "orange accent-4 white-text", :title => "Registrazione allenatore" %></li>
    </ul>

    <!-- Navbar desktop -->
    <nav class="white" role="navigation">
      <div class="nav-wrapper container">
        <a id="logo-container" href="#" class="brand-logo orange-text text-accent-4">FitJoy</a> 
        <ul class="right hide-on-med-and-down">
          <li><%= link_to 'Come Funziona', '#come_funziona', :class => "indigo-text text-darken-4", :title => "Come funziona" %></li>
          <li><%= link_to 'Registrati', '#registrati', :class => "indigo-text text-darken-4", :title => "Registrati" %></li>
          <li><%= link_to 'Sono un allenatore', '#sono_un_allenatore', :class => "orange-text text-accent-4", :title => "Sono un allenatore" %></li>
          <li><%= link_to 'Contatti', '#contacts', :class => "indigo-text text-darken-4", :title => "Contatti" %></li>
          <li><%= link_to 'Blog', 'http://blog.fitjoy.it', :class => "indigo-text text-darken-4", :title => "Blog" %></li>

          <% if user_signed_in? %>
            <li><%= link_to 'Log out', destroy_user_session_path, method: :delete, :class => "indigo-text text-darken-4", :title => "Log out utente" %></li>
          <% else %>
            <% if trainer_signed_in? %>
              <li><%= link_to 'Log out', destroy_trainer_session_path, method: :delete, :class => "indigo-text text-darken-4", :title => "Log out allenatore" %></li>
            <% else %>
              <li><a class="indigo-text text-darken-4 dropdown-button" href="#!" data-activates="dropdown-login" title="Log in">Log in<i class="material-icons right">arrow_drop_down</i></a></li>
              <li><a class="indigo-text text-darken-4 dropdown-button" href="#!" data-activates="dropdown-registrazione" title="Registrazione">Registrazione<i class="material-icons right">arrow_drop_down</i></a></li>
            <% end %>
          <%end %>
          
        </ul>

        <!-- Navbar mobile -->
        <ul id="nav-mobile" class="side-nav">
          <li><%= link_to 'Come Funziona', '#come_funziona', :class => "indigo-text text-darken-4", :title => "Come funziona" %></li>
          <li><%= link_to 'Registrati', '#registrati', :class => "indigo-text text-darken-4", :title => "Registrati" %></li>
          <li><%= link_to 'Sono un allenatore', '#sono_un_allenatore', :class => "orange-text text-accent-4", :title => "Sono un allenatore" %></li>
          <li><%= link_to 'Contatti', '#contacts', :class => "indigo-text text-darken-4", :title => "Contatti" %></li>
          <li><%= link_to 'Blog', 'http://blog.fitjoy.it', :class => "indigo-text text-darken-4", :title => "Blog" %></li>

          <% if user_signed_in? %>
            <li><%= link_to 'Log out', destroy_user_session_path, method: :delete, :class => "indigo-text text-darken-4", :title => "Log out utente" %></li>
          <% else %>
            <% if trainer_signed_in? %>
              <li><%= link_to 'Log out', destroy_trainer_session_path, method: :delete, :class => "indigo-text text-darken-4", :title => "Log out allenatore" %></li>
            <% else %>

              <li class="no-padding">
                <ul class="collapsible collapsible-accordion">

                  <li>
                    <a class="collapsible-header indigo-text text-darken-4">Log in<i class="material-icons">arrow_drop_down</i></a>
                    <div class="collapsible-body">
                      <ul>
                        <li><%= link_to 'Utente', new_user_session_path, :class => "indigo darken-4 white-text", :title => "Log in utente" %></li>
                        <li><%= link_to 'Allenatore', new_trainer_session_path, :class => "orange accent-4 white-text", :title => "Log in allenatore" %></li>
                      </ul>
                    </div>
                  </li>

                  <li>
                    <a class="collapsible-header indigo-text text-darken-4">Registrazione<i class="material-icons">arrow_drop_down</i></a>
                    <div class="collapsible-body">
                      <ul>
                        <li><%= link_to 'Nuovo utente', new_user_registration_path, :class => "indigo darken-4 white-text", :title => "Registrazione utente" %></li>
                        <li><%= link_to 'Nuovo allenatore', new_trainer_registration_path, :class => "orange accent-4 white-text", :title => "Registrazione allenatore" %></li>
                      </ul>
                    </div>
                  </li>

            </ul>
          </li>

            <% end %>

          <% end %>

        </ul>

        <a href="#" data-activates="nav-mobile" class="button-collapse indigo-text text-darken-4"><i class="material-icons">menu</i></a>
      </div>
    </nav>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>FitJoy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

  <!-- SumoMe -->
  <script src="//load.sumome.com/" data-sumo-site-id="aa2dc45c84092878ee7c07fcbabc256518faaaee603234d09b0025a1d8eb0922" async="async"></script>

</head>
<body>

<%= render "layouts/header" %>

   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>

<main class="container">
	<%= yield %>
</main>

<%= render "layouts/footer" %>

</body>

	<script>

    $(document).ready(function(){
    
      // Sidebar
      $('.button-collapse').sideNav({
          menuWidth: 240, // Default is 240
          edge: 'left', // Choose the horizontal origin
          closeOnClick: true // Closes side-nav on <a> clicks, useful for Angular/Meteor
        }
      );

      $('.collapsible').collapsible();

      // Hide sideNav
      //$('.button-collapse').sideNav('hide');
      // Show sideNav
      //$('.button-collapse').sideNav('show');

      // Dropdown
      $('.dropdown-button').dropdown({
           inDuration: 300,
           outDuration: 300,
           constrain_width: true, // Does not change width of dropdown to that of the activator
           gutter: 0, // Spacing from edge
           hover: true, // Activate on hover
           belowOrigin: true // Displays dropdown below the button
           }
      );
    });

      $('.datepicker').pickadate({
  	    selectMonths: true, // Creates a dropdown to control month
  	    selectYears: 80, // Creates a dropdown of 15 years to control year
  	    max: [2016]
	    });

      $('.datepicker_class').pickadate({
        selectMonths: true, // Creates a dropdown to control month
        selectYears: 3, // Creates a dropdown of 15 years to control year
        min: [2016]
      });

	</script>

  <!-- Analytics -->
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-80838948-1', 'auto');
    ga('send', 'pageview');
  </script>

  <!--Start Cookie Script--> 
  <script type="text/javascript" charset="UTF-8" src="http://chs03.cookie-script.com/s/8468e2c5e61c5c3cf706c6cac3407983.js"></script> 
  <!--End Cookie Script-->

</html>

app/views/lezionis/_form.html.erb
<%= form_for(@lezioni) do |f| %>
  <% if @lezioni.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lezioni.errors.count, "error") %> prohibited this lezioni from being saved:</h2>

      <ul>
      <% @lezioni.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titolo %><br>
    <%= f.text_field :titolo %>
  </div>
  <div class="field">
    <%= f.label :prezzo %><br>
    <%= f.text_field :prezzo %>
  </div>
  <div class="field">
    <%= f.label :descrizione %><br>
    <%= f.text_area :descrizione %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date, class: "datepicker_class picker__weekday-display picker__date-display picker__day picker__day--today" %>
  </div>
  <div class="field">
    <%= f.label :park %><br>
    <%= f.text_field :park %>
  </div>
  <div class="field">
    <%= f.label :meeting_point %><br>
    <%= f.text_area :meeting_point %>
  </div>
  <div class="field">
    <%= f.label :equipment %><br>
    <%= f.text_area :equipment %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <!-- <%= f.time_select :time, class: "timepicker" %> -->
  </div>
  <div class="field">
    <%= f.label :minutes %><br>
    <%= f.number_field :minutes %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lezionis/edit.html.erb
<h1>Editing Lezioni</h1>

<%= render 'form' %>

<%= link_to 'Show', @lezioni %> |
<%= link_to 'Back', lezionis_path %>

app/views/lezionis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lezionis</h1>

<table>
  <thead>
    <tr>
      <th>Titolo</th>
      <th>Prezzo</th>
      <th>Descrizione</th>
      <th>Allenatore</th>
      <th>Date</th>
      <th>Parco</th>
      <th>Meeting point</th>
      <th>Equipment</th>
      <th>City</th>
      <th>Time</th>
      <th>Numero di iscritti</th>
      <th>Durata</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lezionis.each do |lezioni| %>
      <tr>
        <td><%= lezioni.titolo %></td>
        <td><%= lezioni.prezzo %></td>
        <td><%= lezioni.descrizione %></td>
        <td><%= lezioni.trainer.name %></td>
        <td><%= lezioni.date %></td>
        <td><%= lezioni.park %></td>
        <td><%= lezioni.meeting_point %></td>
        <td><%= lezioni.equipment %></td>
        <td><%= lezioni.city %></td>
        <td><%= lezioni.time %></td>
        <td><%= lezioni.numero_di_iscritti %></td>
        <td><%= lezioni.minutes %></td>
        <td><%= link_to 'Apri', lezioni %></td>

        <% if lezioni.trainer == current_trainer %>
          <td><%= link_to 'Modifica', edit_lezioni_path(lezioni) %></td>
          <td><%= link_to 'Cancella', lezioni, method: :delete, data: { confirm: 'Sei sicuro?' } %></td>
        <% end %>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lezioni', new_lezioni_path %>

app/views/lezionis/new.html.erb
<h1>New Lezioni</h1>

<%= render 'form' %>

<%= link_to 'Back', lezionis_path %>

app/views/lezionis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titolo:</strong>
  <%= @lezioni.titolo %>
</p>

<p>
  <strong>Prezzo:</strong>
  <%= @lezioni.prezzo %>
</p>

<p>
  <strong>Descrizione:</strong>
  <%= @lezioni.descrizione %>
</p>

<p>
  <strong>Date:</strong>
  <%= @lezioni.date %>
</p>

<p>
  <strong>Park:</strong>
  <%= @lezioni.park %>
</p>

<p>
  <strong>Meeting point:</strong>
  <%= @lezioni.meeting_point %>
</p>

<p>
  <strong>Equipment:</strong>
  <%= @lezioni.equipment %>
</p>

<p>
  <strong>City:</strong>
  <%= @lezioni.city %>
</p>

<p>
  <strong>Time:</strong>
  <%= @lezioni.time %>
</p>

<p>
  <strong>Numero di iscritti:</strong>
  <%= @lezioni.numero_di_iscritti %>
</p>

<p>
  <strong>Durata:</strong>
  <%= @lezioni.minutes %>
</p>

<% if @lezioni.trainer == current_trainer %>
  <%= link_to 'Edit', edit_lezioni_path(@lezioni) %> |
<% end %>
<%= link_to 'Back', lezionis_path %>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>